authentication/urls.py
from django.urls import path
from . import views

app_name = "auth"

urlpatterns = [
    path("log_in/", views.log_in, name="log_in"),
    path("sign_up/", views.sign_up, name="sign_up"),
    path("log_out/", views.log_out, name="log_out"),
    path("<int:pk>/", views.profile, name="profile"),
]

content/urls.py
from django.urls import path
from . import views

app_name = "content"

urlpatterns = [
    path("comments/", views.all_comments, name="all_comments"),
    path("user_content/", views.user_content, name="user_content"),
    path("submit/", views.create_post, name="submit"),
    path("posts/", views.all_posts, name="posts"),
    path("post/<int:pk>", views.post_details, name="post_details"),
    path("post/<int:pk>/update", views.post_update, name="post_update"),
    path("post/<int:pk>/delete", views.post_delete, name="post_delete"),
    path("comment/<int:pk>/update",
         views.comment_update, name="comment_update"),
    path("comment/<int:pk>/delete",
         views.comment_delete, name="comment_delete"),
    path("posts/vote/<int:pk>", views.post_vote, name="post_vote"),
    path("comments/vote/<int:pk>",
         views.comment_vote, name="comment_vote"),
]

old_news/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import news

urlpatterns = [
    path("", news, name="news"),
    path("admin/", admin.site.urls),
    path("auth/", include("authentication.urls")),
    path("content/", include("content.urls")),
]

authentication/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages


def sign_up(request):
    form = UserCreationForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect("auth:log_in")
    return render(request, "sign_up.html", {"form": form})


def log_in(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect("news")
        else:
            messages.info(request,
                          "Try again! username or password is incorrect")
    return render(request, "log_in.html", {})


def log_out(request):
    logout(request)
    return redirect("news")


def profile(request, pk):
    user = User.objects.get(id=pk)
    context = {"user": user}
    return render(request, "profile.html", context)

authentication/templates/log_in.html
<div class="login-page">
  <div class="form">
    <form method="POST" action="">
      {% csrf_token %}
      <h2>Login</h2>
      <p>Username:<br>
        <input type="text" name="username"></p>
      <p>Password:<br>
        <input type="password" name="password"></p>
      <button type="submit"> Login </button>
      <p class="message">Don't have an account? <a href="{% url 'auth:sign_up' %}">Sign Up</a></p>
    </form>
  </div>
</div>

authentication/templates/profile.html
{% extends 'base.html' %}

{%  block content %}
    <h2>Profile</h2>
    <p>Username : {{ user.username }}</p>
    <p>Date joined : {{ user.date_joined }}</p>
{% endblock %}

authentication/templates/sign_up.html
{% extends 'base.html' %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}