content/urls.py
from django.urls import path
from . import views

app_name = "content"

urlpatterns = [
    path("comments/", views.all_comments, name="all_comments"),
    path("user_content/", views.user_content, name="user_content"),
    path("submit/", views.create_post, name="submit"),
    path("posts/", views.all_posts, name="posts"),
    path("post/<int:pk>", views.post_details, name="post_details"),
    path("post/<int:pk>/update", views.post_update, name="post_update"),
    path("post/<int:pk>/delete", views.post_delete, name="post_delete"),
    path("comment/<int:pk>/update",
         views.comment_update, name="comment_update"),
    path("comment/<int:pk>/delete",
         views.comment_delete, name="comment_delete"),
    path("posts/vote/<int:pk>", views.post_vote, name="post_vote"),
    path("comments/vote/<int:pk>",
         views.comment_vote, name="comment_vote"),
]

old_news/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import news

urlpatterns = [
    path("", news, name="news"),
    path("admin/", admin.site.urls),
    path("auth/", include("authentication.urls")),
    path("content/", include("content.urls")),
]

content/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import URLValidator
from django.utils import timezone


class Post(models.Model):
    title = models.CharField(max_length=300)
    link = models.URLField(max_length=200, validators=[URLValidator])
    creation_date = models.DateTimeField(auto_now_add=True, editable=False)
    up_votes = models.BigIntegerField()
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="author_posts"
    )
    users_voted = models.ManyToManyField(User)

    def __str__(self):
        return self.link

    def get_author(self):
        return self.author

    def get_comments(self):
        return list(self.post_comments.all())

    def get_users_voted(self):
        return list(self.users_voted.all())

    def when_published(self):
        now = timezone.now()
        since = now - self.creation_date
        days = since.days
        seconds = since.seconds

        if days == 0:
            if seconds >= 3600:
                return f"{int(seconds/3600)} hours ago"
            else:
                return f"{int(seconds / 60)} minutes ago"
        else:
            return f"{days} days ago"


class Comment(models.Model):
    content = models.TextField()
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name="post_comments"
    )
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="author_comments"
    )
    up_votes = models.BigIntegerField()
    users_voted = models.ManyToManyField(User)
    creation_date = models.DateTimeField(auto_now_add=True, editable=False)

    def __str__(self):
        return self.content

    def get_author(self):
        return self.author

    def get_post(self):
        return self.post

    def get_users_voted(self):
        return list(self.users_voted.all())

    def when_published(self):
        now = timezone.now()
        since = now - self.creation_date
        days = since.days
        seconds = since.seconds

        if days == 0:
            if seconds >= 3600:
                return f"{int(seconds/3600)} hours ago"
            else:
                return f"{int(seconds / 60)} minutes ago"
        else:
            return f"{days} days ago"

content/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            "title",
            "link",
        ]


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            "content",
        ]

content/views.py
from django.shortcuts import render, redirect
from .models import Post, Comment
from .forms import PostForm, CommentForm
from background_task import background


def all_posts(request):
    context = {'posts': Post.objects.all()}
    return render(request, "all_posts.html", context)


def create_post(request):
    context = {}
    form = PostForm(request.POST or None)
    if form.is_valid():
        new_post = form.save(commit=False)
        new_post.up_votes = 0
        new_post.author = request.user
        new_post.save()
        context = {
            "link": new_post.link,
            "title": new_post.title,
            "author": request.user.username,
        }
    context["form"] = PostForm()
    return render(request, "create_post.html", context)


def post_details(request, pk):
    post = Post.objects.get(id=pk)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        new_comment = form.save(commit=False)
        new_comment.post = Post.objects.get(id=pk)
        new_comment.up_votes = 0
        new_comment.author = request.user
        new_comment.save()
    context = {}
    context["form"] = CommentForm()
    context["post"] = post
    return render(request, "post_details.html", context)


def post_update(request, pk):
    post = Post.objects.get(id=pk)
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post.title = form.cleaned_data["title"]
            post.link = form.cleaned_data["link"]
            post.save()
            return redirect("content:user_content")
    else:
        form = PostForm(instance=post)
    context = {"form": form}
    return render(request, "post_update.html", context)


def post_delete(request, pk):
    post = Post.objects.get(id=pk)
    post.delete()
    return redirect("content:user_content")


def all_comments(request):
    context = {"comments": Comment.objects.all()}
    return render(request, "all_comments.html", context)


def comment_update(request, pk):
    comment = Comment.objects.get(id=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment.content = form.cleaned_data["content"]
            comment.save()
            return redirect("content:user_content")
    else:
        form = CommentForm(instance=comment)
    context = {"form": form}
    return render(request, "comment_update.html", context)


def comment_delete(request, pk):
    comment = Comment.objects.get(id=pk)
    comment.delete()
    return redirect("content:user_content")


def user_content(request):
    posts = Post.objects.filter(author=request.user)
    comments = Comment.objects.filter(author=request.user)
    context = {"posts": posts, "comments": comments, "user": request.user}
    return render(request, "user_content.html", context)


def post_vote(request, pk):
    post = Post.objects.get(id=pk)
    if request.user in post.get_users_voted():
        post.up_votes -= 1
        post.users_voted.remove(request.user)
    else:
        post.up_votes += 1
        post.users_voted.add(request.user)
    post.save()
    posts = Post.objects.all()
    return render(request, "all_posts.html", {"posts": posts})


def comment_vote(request, pk):
    comment = Comment.objects.get(id=pk)
    if request.user in comment.get_users_voted():
        comment.up_votes -= 1
        comment.users_voted.remove(request.user)
    else:
        comment.up_votes += 1
        comment.users_voted.add(request.user)
    comment.save()
    comments = Comment.objects.all()
    return render(request, "all_comments.html", {"comments": comments})


@background(schedule=60)
def clear_votes():
    for comment in Comment.objects.all():
        comment.up_votes = 0
        comment.users_voted.clear()
        comment.save()
    for post in Post.objects.all():
        post.up_votes = 0
        post.users_voted.clear()
        post.save()


clear_votes(repeat=60 * 60 * 24)

content/templates/all_comments.html
{% extends 'base.html' %}

{%  block content %}
<!-- Add icon library -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<ol>
    {% for comment in comments|dictsortreversed:"creation_date" %}
    <li>
        <!-- Use an element to toggle between a like/dislike icon -->
        {{ comment.get_author }} commented on
        <a href="{{ comment.get_post.link }}">{{ comment.get_post.title }}</a>
        ({{comment.when_published}}) : <br/>
        <b>{{ comment.content }}</b><br/>
        {% if user in comment.get_users_voted %}
            <a href="{% url 'content:comment_vote' comment.id %}">
                <i class="fa fa-thumbs-down"></i></a>{{ comment.up_votes }} votes<br/><br/>
        {% else %}
            <a href="{% url 'content:comment_vote' comment.id %}">
                <i class="fa fa-thumbs-up"></i></a>{{ comment.up_votes }} votes<br/><br/>
        {% endif %}


    {% endfor %}
</ol>
{% endblock %}

content/templates/all_posts.html
{% extends 'base.html' %}

{%  block content %}

<!-- Add icon library -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<ol>
    {% for post in posts|dictsortreversed:"creation_date" %}
    <li>
        <!-- Use an element to toggle between a like/dislike icon -->
        {% if user in post.get_users_voted %}
            <a href="{% url 'content:post_vote' post.id %}"><i class="fa fa-thumbs-down"></i></a>
        {% else %}
            <a href="{% url 'content:post_vote' post.id %}"><i class="fa fa-thumbs-up"></i></a>
        {% endif %}

        <a href="{{ post.link }}">{{ post.title }}</a> by {{ post.get_author }}<br/>
        {{ post.up_votes }} upvotes, {{ post.when_published }},

        <a href="{% url 'content:post_details' post.id %}">
        {% if post.get_comments|length > 1 %}
            {{ post.get_comments|length }} comments
        {% elif post.get_comments|length == 1 %}
            1 comment
        {% else %}
            comment
        {% endif %}</a><br/><hr/></li>
    {% endfor %}
</ol>
{% endblock %}

content/templates/comment_update.html
{% extends 'base.html' %}

{%  block content %}
<form method="POST">
    <!-- Security token -->
    {% csrf_token %}
    <h2>Update comment</h2>
    {% for field in form %}
      <p>
        {{ field.label_tag }}
        {{ field }}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Update</button>
  </form>
{% endblock %}

content/templates/create_post.html
{% extends 'base.html' %}

{%  block content %}
<form method="POST" enctype="multipart/form-data">
    <!-- Security token -->
    {% csrf_token %}
    {% if title %}
        <p>New post created :
            <a href= "{{ link }}">{{ title }}</a> by {{ author }}</p>
    {% endif %}

    {% for field in form %}
      <p>
        {{ field.label_tag }}
        {{ field }}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Submit</button>
  </form>
{% endblock %}

content/templates/post_details.html
{% extends 'base.html' %}

{%  block content %}

<!-- Add icon library -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<h2><a href= "{{ post.link }}">{{ post.title }}</a> by {{ post.get_author }}</h2><hr/>

<form method="POST" enctype="multipart/form-data">
    <!-- Security token -->
    {% csrf_token %}

    {% for field in form %}
      <p>
          Add comment:<br/>
        {{ field }}<br/>
          <button type="submit">Submit</button>
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
  </form>


{% for comment in post.get_comments|dictsortreversed:"creation_date" %}
    <!-- Use an element to toggle between a like/dislike icon -->
    {{ comment.get_author }} ({{comment.when_published}}) : {{ comment.content }}<br/>
    {% if user in comment.get_users_voted %}
        <i class="fa fa-thumbs-down"></i>{{ comment.up_votes }} votes<br/><br/>
    {% else %}
        <i class="fa fa-thumbs-up"></i>{{ comment.up_votes }} votes<br/><br/>
    {% endif %}
{% endfor %}

{% endblock %}

content/templates/post_update.html
{% extends 'base.html' %}

{%  block content %}
<form method="POST">
    <!-- Security token -->
    {% csrf_token %}
    <h2>Update post</h2>
    {% for field in form %}
      <p>
        {{ field.label_tag }}
        {{ field }}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Update</button>
  </form>
{% endblock %}

content/templates/user_content.html
{% extends 'base.html' %}

{%  block content %}
<div class="grid-container">

    <div class="left_column">
        <h2> Posts by {{ user.username }}</h2>
        {% for post in posts|dictsortreversed:"creation_date" %}
            <div style="font-size:1.5vw"><a href="{{ post.link }}">{{ post.title }}</a></div>
            <div style="font-size:1vw">{{ post.up_votes }} upvotes, {{ post.when_published }},
                {{post.get_comments|length}} comments </div>

            <a href="{% url 'content:post_update' post.id %}">Update</a>
            <a href="{% url 'content:post_delete' post.id %}"
               onclick="return confirm('Are you sure you want to delete this post?')">Delete</a><hr/>
        {% endfor %}
    </div>

    <div class="right_column">
        <h2> Comments by {{ user.username }} </h2>
         {% for comment in comments|dictsortreversed:"creation_date" %}
            <div style="font-size:1.5vw">{{ comment.content }}</div>
            <div style="font-size:1vw">Comment on <a href="{{ comment.get_post.link }}">{{ comment.get_post.title }}</a></div>
            <div style="font-size:1vw">{{ comment.up_votes }} upvotes, {{ comment.when_published }}</div>

             <a href="{% url 'content:comment_update' comment.id %}">Update</a>
             <a href="{% url 'content:comment_delete' comment.id %}"
               onclick="return confirm('Are you sure you want to delete this comment?')">Delete</a><hr/>
         {% endfor %}
    </div>
</div>
{% endblock %}